name: Continuous integration

on: [pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Code analysis 
        run: npm run lint

      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
